#!/bin/bash
export SHELL=/bin/zsh
export EDITOR=nvim
export PAGER='less'
export GOPATH=$HOME/go
export PYENV_ROOT="$HOME/.pyenv"

# Path
export PATH="$GOPATH/bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export PATH="$(brew --prefix)/bin:$PATH"
export PATH="/usr/local/go/bin:$PATH"
export PATH="/usr/local/opt/llvm/bin:$PATH"


# Yarn
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

# Bat
export BAT_THEME="Dracula"

